//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealeronTest.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DealeronTest.Localizations.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diwedd.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Max Coordinates as X Y: .
        /// </summary>
        internal static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to detect both X and Y max co-ordinates for grid..
        /// </summary>
        internal static string GridBothMaxError {
            get {
                return ResourceManager.GetString("GridBothMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input grid coordinates contained a negative..
        /// </summary>
        internal static string GridCoordNegative {
            get {
                return ResourceManager.GetString("GridCoordNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to detect max X co-ordinate..
        /// </summary>
        internal static string GridMaxXError {
            get {
                return ResourceManager.GetString("GridMaxXError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to detect max Y co-ordinate..
        /// </summary>
        internal static string GridMaxYError {
            get {
                return ResourceManager.GetString("GridMaxYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid instruction somehow made it into the path. Ceasing Run..
        /// </summary>
        internal static string InvalidPathInstruction {
            get {
                return ResourceManager.GetString("InvalidPathInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iaith.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That was an invalid language code..
        /// </summary>
        internal static string LanguageCodeError {
            get {
                return ResourceManager.GetString("LanguageCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input new language code:.
        /// </summary>
        internal static string LanguagePrompt {
            get {
                return ResourceManager.GetString("LanguagePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dewisiadau Dewislen: ailosod - yn clirio maint grid a rovers.  rhedeg - dechrau crwydro crwydro.  iaith - newid iaith.  diwedd - yn cau rhaglen.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover Origin and Direction: .
        /// </summary>
        internal static string OriginInput {
            get {
                return ResourceManager.GetString("OriginInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover Path: .
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press enter to restart..
        /// </summary>
        internal static string PressEnter {
            get {
                return ResourceManager.GetString("PressEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ailosod.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to detect rover initial direction..
        /// </summary>
        internal static string RoverDirectionError {
            get {
                return ResourceManager.GetString("RoverDirectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to detect both X and Y co-ordinates and direction for Rover..
        /// </summary>
        internal static string RoverLocationAndDirectionError {
            get {
                return ResourceManager.GetString("RoverLocationAndDirectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover new location: {0} and direction: {1}.
        /// </summary>
        internal static string RoverResponse {
            get {
                return ResourceManager.GetString("RoverResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to detect rover x co-ordinate..
        /// </summary>
        internal static string RoverXError {
            get {
                return ResourceManager.GetString("RoverXError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover location would exceed grid max X coordinate. Can not continue..
        /// </summary>
        internal static string RoverXMaxError {
            get {
                return ResourceManager.GetString("RoverXMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover location would exceed grid origin X cooridnate. Can not continue..
        /// </summary>
        internal static string RoverXMinError {
            get {
                return ResourceManager.GetString("RoverXMinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to detect rover y co-ordinate..
        /// </summary>
        internal static string RoverYError {
            get {
                return ResourceManager.GetString("RoverYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover location would exceed grid max Y coordinate. Can not continue..
        /// </summary>
        internal static string RoverYMaxError {
            get {
                return ResourceManager.GetString("RoverYMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover location would exceed grid origin Y coordinate. Can not continue..
        /// </summary>
        internal static string RoverYMinError {
            get {
                return ResourceManager.GetString("RoverYMinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rhedeg.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Safety. This will be a full restart from grid definition..
        /// </summary>
        internal static string SafetyRestart {
            get {
                return ResourceManager.GetString("SafetyRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space - The Final Frontier.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
